/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Job */
        post: operations["create_job_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HaltReason
         * @enum {string}
         */
        HaltReason: "completed" | "max_time";
        /** Job */
        Job: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** @default pending */
            status: components["schemas"]["JobStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            result?: components["schemas"]["JobResult"] | null;
        };
        /** JobCreated */
        JobCreated: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
        };
        /** JobRequest */
        JobRequest: {
            /** Source */
            source: string;
            flags?: components["schemas"]["KleeFlags"];
        };
        /** JobResult */
        JobResult: {
            /** Test Cases */
            test_cases: components["schemas"]["TestCase"][];
            /** Messages */
            messages: string;
            /** Warnings */
            warnings: string;
            /** Stats */
            stats: {
                [key: string]: number;
            };
            /** Compile Error */
            compile_error?: string | null;
            halt_reason?: components["schemas"]["HaltReason"] | null;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "pending" | "running" | "parsing" | "done" | "failed";
        /** KleeFlags */
        KleeFlags: {
            /**
             * Max Time
             * @default 60
             */
            max_time: number;
            /**
             * Max Memory
             * @default 512
             */
            max_memory: number;
        };
        /** TestCase */
        TestCase: {
            /** Name */
            name: string;
            /** Inputs */
            inputs: {
                [key: string]: string;
            };
            /** Error */
            error?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_job_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
